[package]
name = "kosmos"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
ilios-types = { path = "../ilios-types" }
serde = { version = "1.0", features = ["derive"] }
