[package]
name = "screen"
version = "0.1.0"
authors = ["Enrique <niofis@gmail.com>"]
edition = "2024"

[dependencies]
clap = "4"
time = "0.3"
ilios = { path = "../ilios" }
ilios-types = { path = "../ilios-types" }


[dependencies.sdl2]
version = "0.35"
default-features = false
features = ["gfx"]
