[package]
name = "light"
version = "0.1.0"
authors = ["Enrique <niofis@gmail.com>"]
edition = "2024"

[profile.dev]
split-debuginfo = "unpacked"

[dependencies]
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
rayon = "1.10"
