[package]
name = "photon"
version = "0.1.0"
authors = ["Enrique <niofis@gmail.com>"]
edition = "2024"

[profile.dev]
split-debuginfo = "unpacked"

[dependencies]
bincode = "2.0.0-rc.3"
clap = "4"
chrono = "0.4.31"
light = { path = "../light" }
time = "0.3"
png = "0.17.10"
